# Generated by Django 5.1.2 on 2024-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_instructor_course_course_overview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_picture',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='instructors'),
        ),
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
